<?php

namespace AppBundle\Repository;

/**
 * Avis_comRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Avis_comRepository extends \Doctrine\ORM\EntityRepository
{
}
