<?php

namespace AppBundle\Repository;

/**
 * Avis_articleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Avis_articleRepository extends \Doctrine\ORM\EntityRepository
{
}
